apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: drift-shield-jenkins:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: AWS_DEFAULT_REGION
              value: "ap-south-1"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret_key
